# Site settings
title:          jayiuk
description:    "Rain is a simple and clean Jekyll theme with focus on content."
url:            https://github.com/jayiuk/jayiuk.github.io

# Author
author:
  name:         Jeon Younguk
  email:        jayiuk987@gmail.com
  url:          https://jayiuk.github.io/

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Related posts settings
related_posts_section:
  max_count:        10
  min_common_tags:  2

# Links to social media
social:
  email: jayiuk987@gmail.com
  github: https://github.com/jayiuk
