title: jayiuk blog
logo_img: /assets/img/icons/golasblog_logo.svg
favicon: /assets/favicon.ico
description: description
global_tags: jekyll theme simplex golasblog responsive html5
copyright: © Jeon Young-uk 2023
url: "https://jayiuk.github.io/"
baseurl: ""

theme: jekyll-theme-simplex
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"